export const TOGGLE_FLAG = 'TOGGLE_FLAG';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const TOGGLE_SPLASH = 'TOGGLE_SPLASH';
export const TOGGLE_SUCCESS = 'TOGGLE_SUCCESS';
